version: '3.8'

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.5
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: quay.io/debezium/kafka:2.5
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper

  mysql:
    image: quay.io/debezium/example-mysql:2.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

  connect:
    image: quay.io/debezium/connect:2.5
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
    links:
      - kafka:kafka
      - mysql:mysql
    command: ["bash", "-c", "sleep 20 && curl -i -X POST -H 'Accept:application/json' -H 'Content-Type:application/json' localhost:8083/connectors/ -d '{ \"name\": \"inventory-connector\", \"config\": { \"connector.class\": \"io.debezium.connector.mysql.MySqlConnector\", \"tasks.max\": \"1\", \"database.hostname\": \"mysql\", \"database.port\": \"3306\", \"database.user\": \"debezium\", \"database.password\": \"dbz\", \"database.server.id\": \"184054\", \"topic.prefix\": \"dbserver1\", \"database.include.list\": \"inventory\", \"schema.history.internal.kafka.bootstrap.servers\": \"kafka:9092\", \"schema.history.internal.kafka.topic\": \"schemahistory.inventory\" } }'"]

  watcher:
    image: quay.io/debezium/kafka:2.5
    container_name: watcher
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    command: ["watch-topic", "-a", "-k", "dbserver1.inventory.customers"]
