version: '3.8'

services:
  mysql_con:
    container_name: mysql_node_connection
    environment: 
      - MAINTAINER=ruhul@ba-systems.com
      - DB_HOST=193
      - DB_USER=etl_n_nif
      - DB_PASS=g9^5
      - DB_NAME=mutasal
      - DB_PORT=3306
    ports:
      - 3000:3000
    volumes:
      - /home/ruhul/image_testing_process/data_volume:/var/opt
    build:
      dockerfile: mncon_dockerfile
    restart: "no"

  file_copier:
    image: alpine
    container_name: file_copier_container
    depends_on:
      - mysql_con
    volumes:
      - /home/ruhul/image_testing_process/data_volume:/var/opt
      - /home/ruhul/image_testing_process/data_volume:/host
    entrypoint: ["/bin/sh", "-c", "while [ \"$(docker inspect -f '{{.State.Status}}' mysql_node_connection)\" != \"exited\" ]; do sleep 1; done && cp /var/opt/log.txt /host/"]
