version: '1.0.0'
services:
  mysql_con:
    container_name: mysql_node_connection
    environment: 
      - MAINTAINER=ru.com
      - DB_HOST=192..3
      - DB_USER=etl_munif
      - DB_PASS=g9^5
      - DB_NAME=muisal
      - DB_PORT=3306
    ports:
      - 3000:3000
    volumes:
      - ./myfile.txt:/var/opt/myfile.txt
    build:
      dockerfile: mncon_dockerfile