version: 1.0.0
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888"
    volumes:
      - ./zkafka_data/zookeeper1/zk-data:/var/lib/zookeeper/data
      - ./zkafka_data/zookeeper1/zk-txn-logs:/var/lib/zookeeper/log
    ports:
      - 2181:2181
  zookeeper2:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888"
    volumes:
      - ./zkafka_data/zookeeper2/zk-data:/var/lib/zookeeper/data
      - ./zkafka_data/zookeeper2/zk-txn-logs:/var/lib/zookeeper/log

  zookeeper3:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888"
    volumes:
      - ./zkafka_data/zookeeper3/zk-data:/var/lib/zookeeper/data
      - ./zkafka_data/zookeeper3/zk-txn-logs:/var/lib/zookeeper/log
  zookeeper4:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_SERVER_ID: 4
      ZOOKEEPER_CLIENT_PORT: 2184
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888"
    volumes:
      - ./zkafka_data/zookeeper4/zk-data:/var/lib/zookeeper/data
      - ./zkafka_data/zookeeper4/zk-txn-logs:/var/lib/zookeeper/log
  zookeeper5:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_SERVER_ID: 5
      ZOOKEEPER_CLIENT_PORT: 2185
      ZOOKEEPER_SERVERS: "zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888;zookeeper4:2888:3888;zookeeper5:2888:3888"
    volumes:
      - ./zkafka_data/zookeeper5/zk-data:/var/lib/zookeeper/data
      - ./zkafka_data/zookeeper5/zk-txn-logs:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092
    volumes:
      - ./zkafka_data/kafka1:/var/lib/kafka/data
  kafka2:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9992
    ports:
      - 9093:9093
    volumes:
      - ./zkafka_data/kafka2:/var/lib/kafka/data
  kafka3:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9993
    ports:
      - 9094:9094
    volumes:
      - ./zkafka_data/kafka3:/var/lib/kafka/data
  kafka4:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka4:9095
      KAFKA_BROKER_ID: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9994
    ports:
      - 9095:9095
    volumes:
      - ./zkafka_data/kafka4:/var/lib/kafka/data

  kafka5:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka5:9096
      KAFKA_BROKER_ID: 5
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9995
    ports:
      - 9096:9096
    volumes:
      - ./zkafka_data/kafka5:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092,kafka2:9093,kafka3:9094,kafka4:9095,kafka5:9096"
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
      - "kafka4"
      - "kafka5"

  connect:
    image: quay.io/debezium/connect:1.9
    ports:
      - 8083:8083
    links:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
    environment:
      BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094,kafka4:9095,kafka5:9096"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
      CONNECTOR_CLASS: "io.debezium.connector.mysql.MySqlConnector"
      # MySQL connection details
      DATABASE_HOSTNAME: "172.18.0.1" # database host IP address
      DATABASE_PORT: "3306"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "P@ssW0rd"
      DATABASE_SERVER_ID: "1"
      DATABASE_SERVER_NAME: "RuhulAmin"
      DATABASE_HISTORY_KAFKA_TOPIC: "schema-changes.cdc_log"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper1:2181"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://schema-registry:8081,http://172.18.0.1:8081"
    ports:
      - 8081:8081
    depends_on: [zookeeper1, kafka1,kafka2,kafka3,kafka4,kafka5]