version: '1.0.0'
services:
  relational_db_mysql:
    image: mysql:latest
    environment: 
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PASSWORD=ruhul
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=employee
      - MYSQL_ROOT_PASSWORD=ruhul
    ports:
      - 3000:3000
    volumes:
      - ./mysql-data:/var/lib/mysql

