version: '3.8'

services:
  nifi:
    build: .
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=single-user-provider
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=YourSecurePassword
      - NIFI_SECURITY_KEYSTORE=/opt/nifi/nifi-current/conf/keystore.jks
      - NIFI_SECURITY_KEYSTORE_TYPE=JKS
      - NIFI_SECURITY_KEYSTORE_PASSWD=keystorepassword
      - NIFI_SECURITY_TRUSTSTORE=/opt/nifi/nifi-current/conf/truststore.jks
      - NIFI_SECURITY_TRUSTSTORE_TYPE=JKS
      - NIFI_SECURITY_TRUSTSTORE_PASSWD=truststorepassword
    restart: always